### PR TITLE
Overhaul save & export options

### PR DESCRIPTION
**Pull request by JPSchellenberg**

### CODE REVIEW

**Comment by sr258** [comment]
It would be good to give the user a choice how the html exporter should export resources: inline in the html bundle or as separate files. h5p-server's HtmlExporter supports both variants, but they need to be exposed in the UI somehow. 

An option would be to have two seperate menu entries in the "File" menu and a choice when you click on the <> button in the editor window.

Alternatively we could display a modal that gives you the choice (might be something we need anyway in the future to configure the reporting component of the package)

**Comment by JPSchellenberg** [comment]
I agree. We should offer both options, but I would like to keep the process as simple as possible as a lot of people do not understand what the difference between inline resources or external resources. 
I am afraid that two entries in the menu might confuse a lot of users. (Keep in mind the average technical knowledge of a teacher ;D)

A Modal might also be a bit cumbersome as the system "save as" dialog pops up right after that.

My idea would be to have a default way of exporting, which is configurable through a settingspage in the app-config.

**Comment by sr258** [comment]
I think putting the option into global settings is not very discoverable. No-one is going to know that you can change modes, except if they stumble over it by chance.

Not sure if this is possible in Electron, but one way might be to allow the user to select the filetype in the save file picker. We could offer a selection like this:
'.html (all-in-one HTML bundle)'
'.html (all-in-one HTML bundle with report generator)' 
'.zip (HTML file with separate images, videos und audio files)'
'.zip (HTML file with separate images, videos und audio files and report generator)'

This way of changing file formats is quite common (the MS Office products do it that way), so it might be intuitive enough for people to find it. And we don't have to implement weird modals.

**Comment by sr258** [comment]
One thing: if we don't have the HTML buttons we need some kind of saving / loading indicator. My favourite would be to fully block the UI (gray it out) and display a spinner in the centre.

**Comment by JPSchellenberg** [comment]
The loadingIndicator should show (blue progress bar). I will try to grey the ui out.

**Comment by JPSchellenberg** [comment]
It looks good that we can handle the different exports via the system dialog: 😄 
Screenshot 2021-01-06 at 14 53 49

I just need to find out how to retrieve the chosen format...

**Comment by JPSchellenberg** [comment]
It looks like this option is only for defining which file types can be overwritten..

Or do you see a solution?
https://www.electronjs.org/docs/api/dialog#dialogshowsavedialogbrowserwindow-options

**Comment by JPSchellenberg** [comment]
Ok, changing the format changes the extension in the name field:
Screenshot 2021-01-06 at 15 10 46

 We could use that to determine from the filename how it should be exported, but we would have to come up with extension-names for every case.

like .`html-inline` for html with inline resources. We would then now inside electron to export a html with inline resources and then we would have to change the extension back to a normal `.html`

It is a bit hacky.. could you confirm that this would work on windows too?

**Comment by sr258** [comment]
It's indeed a bit hacky to append something that is removed later...

But:
html-external should be zip anyway, as we need to put the resources files into a package somehow.
html-internal can then become html
and h5p can stay h5p

This way the extensions in the list are exactly the ones you'd expect. The question remains how we can put in further options (report generator). A modal after the user has selected the file would be acceptable I think.

I can test this on Windows later, but I don't think it will be a problem.

**Comment by sr258** [comment]
The file saver dialog works in Windows as expected:
image

**Comment by JPSchellenberg** [comment]
How do we want to differentiate between saving & exporting? 
Should the .h5p option only be available in the saving dialog while .html and .zip are in the export dialog or should everything be in the save-dialog?

**Comment by sr258** [comment]
I think there are arguments for both ways. I'd prefer having an "export" menu entry, as it makes it clearer that the file can't be reused then.

**Comment by JPSchellenberg** [comment]
The export as zip is not implemented yet as the html-exporter does not support it yet, but we can add that later.

**Review by sr258 — CHANGES_REQUESTED** [review]
If you don't add an extension to the exported filename, the file will have none. The exporter should append the .html extension if the user has specified none.

If you abort the file picker dialog, you get an error notification, which is not really useful, as there was not real error.

Except for these two small things, the PR is ready to be merged.

**Comment by JPSchellenberg** [comment]
> If you abort the file picker dialog, you get an error notification, which is not really useful, as there was not real error.

That should not happen. I fixed that a few commits ago. Did you have the latest commit?

**Review by sr258 — APPROVED** [review]

**Pull request merged**
