### PR TITLE
fix(analytics): improve error-handling

### PR DESCRIPTION
**Pull request by JPSchellenberg**
Hey,

I started to work on the analytics-issues and I worked out some things:

- You can now import .lumi files from different content-types. They are displayed as different lists. Unfortunately I can not determine the title of the content-type from the contentJson included in the report-file. Any ideas how to make it clear that there are more than one content-type on the page?

- I added a list for "broken files". Files that did not validate for some reasons:
1. file did not parse -> no valid json
2. file does not include the contentJson 
3. file contains invalid interactions
4. file contains invalid statements

- Even if one or several file(s) are broken all others files are imported, analyzed and displayed. 

Any thoughts?

### CODE REVIEW

**Comment by sr258** [comment]
Great job! Things are much better now and much more clear to the user.

I think having multiple tables is fine for now. We should include the title of the content in the reporter in the future. We can get it from the H5P content metadata object.

I've added locales for the new errors.

i18next supports plurals, so you can do stuff like:
```
                "brokenFiles": "{{numberBrokenFiles}} broken file found",
                "brokenFiles_plural": "{{numberBrokenFiles}} broken files found"
```

It's nicer for the users and the auto-translate tools also work better.

I also added case-insensitivity, as one of the sample files we received with the bug report had the extension '.LUMI'. It was not detected.

I can open the test folder "invalid-interactions" without any error message. Is this intentional?

I think the PR is ready to be merged.

**Review by sr258 — APPROVED** [review]

**Comment by sr258** [comment]
While fixing the plurals I've noticed that the language string notifications->analytics->import->brokenFiles is unused. Am I correct here?

**Comment by JPSchellenberg** [comment]
Yes, I removed it for now as it was too fragile for now.

**Comment by JPSchellenberg** [comment]
> I can open the test folder "invalid-interactions" without any error message. Is this intentional?

Yes, this is intentional. But it should show that there are broken files in that folder.

**Pull request merged**
