### PR TITLE
fix(settings): provide privacypolicy URL&change default settings for mas

### PR DESCRIPTION
**Pull request by JPSchellenberg**
Hey,

Apple wants us to display the URL of the privacy policy and have all settings set to false in default, so I changed the SetupDialog to comply with Apple standards.

### CODE REVIEW

**Comment by sr258** [comment]
I‘ve read up a bit and I think our current practice needs to be changed in general: https://datenschutz-generator.de/bgh-cookies-opt-in-faq-checkliste/ 

The best solution might be to have two buttons: „accept selected“ and „accept all“. On mas there’s only the first and all checkboxes are unchecked. On other platforms only the necessary processing is pre-selected.

**Comment by JPSchellenberg** [comment]
I changed the default settings to false and added a "accept all" and "accept selected" button. I also added a link to the privacy policy in the settings under "general" as a link to the privacy policy has to be accessible all the time.

With these changes we should comply with Apples guidelines.

**Comment by sr258** [comment]
Not sure if Apple allows the "accept all" button. The law / courts seem to do so, but from what I read a few days ago (not sure about the exact words), Apple wants us to make users click all the checkboxes one by one and then consent. So I would hide the "accept all" button on Mac.

**Comment by JPSchellenberg** [comment]
In the guideline I read was only mentioned that it should not set to true on default. I would try and see what their review team has to say.

**Pull request merged**
