### PR TITLE
feat(library-management): add h5p-library-management to settings

### PR DESCRIPTION
**Pull request by JPSchellenberg**

### CODE REVIEW

**Comment by JPSchellenberg** [comment]
This PR can be reviewed as soon as #1433 is merged into master and this branch.

**Comment by sr258** [comment]
Great job!

My usual nitpicky remarks: ;)

The left margin of the settings dialog content is incorrect if the window isn't very wide: 
image

The color of the "upload and install library" button is unusual.

If you delete a library, it's still in the list. The list should be updated.

It would be useful do display an indication why many libraries can't be deleted, e.g. a lock symbol with a hover text ("cannot be delted, because it is used in ... other libraries").

**Comment by JPSchellenberg** [comment]
> Great job!

Thank you, but the most code is from you :D

> My usual nitpicky remarks: ;)

They are great.. I miss a lot of those things as I am too focused on other things.. So PR Review do actually make a lot of sense.

**Comment by sr258** [comment]
Looks good! We should first merge in #1443 and then auto-localize the locales to avoid merge conflicts in all the language files. 

The "Installed H5P libraries" title is fixed and doesn't scroll: (always hovers at the same position)
Bildschirmfoto 2021-04-15 um 14 25 54

The margin between the details button and the delete/disabled button should be bigger:
Bildschirmfoto 2021-04-15 um 14 27 58

**Pull request merged**
