### PR TITLE
Add bug reporting tool

### PR DESCRIPTION
**Pull request by JPSchellenberg**
Hey,
to get a hold on the increasing (incomplete) bug reports I added sentry as bug-reporting tool. You can opt-in and out from the settings dialog and are asked to consent on the first start-up.
What do you think? Is something missing?

### CODE REVIEW

**Review by sr258 — CHANGES_REQUESTED** [review]
The code looks fine in general. (tests don't pass yet, however).

We definitely need to add more information about data collection to the settings / opt-in dialog. We should include a link to the app's privacy policy (https://next.lumi.education/app/privacy-policy) and update the privacy policy to reflect the change (not transmitted to Sentry but to us; also the data categries aren't correct any more).

**Comment by sr258** [comment]
And it would also be good to have a checkbox on first startup that asks for the user's consent to the privacy policy in general. The app does transmit data to third parties in some cases and this requires consent as well.

**Comment by JPSchellenberg** [comment]
> And it would also be good to have a checkbox on first startup that asks for the user's consent to the privacy policy in general. The app does transmit data to third parties in some cases and this requires consent as well.

Do you mean the h5p hub or anything else?

**Comment by JPSchellenberg** [comment]
The privacy policy has to be accepted in order to use the app, right? Because I don't see a workaround with the h5phub / GitHub Auto Update.

**Comment by sr258** [comment]
Yes, the H5P and others (see privacy policy)

**Comment by sr258** [comment]
Transmitting data is fine, if there is no other way of the program to work properly. We still have to inform the user about it at least. Ideally, the auto-updates only run after the consent, but I'm not sure if this is possible with the GitHub auto-update.

**Comment by sr258** [comment]
Looks good! I've haven't checked all the code in detail, but I've seen some commented out code, which could probably be fully removed... 

One question about the behaviour of the app: What happens when a user disables one of the options in the settings when the program is already active? Do we need a restart then?

The next step would be to update the pivacy policy on the homepage. I think it would be best to group the data categories by  consent, so that it's transparent what you consent to. We could also add deep links to the consent dialog so that users can see what exactly they consent to. We also need to remove the old subprocessors and add Scaleway as a new contractor.

**Comment by JPSchellenberg** [comment]
The services (autoupdate, bur report, user statistics) always check the consent right before they send data. If you disable it, it will immediately take effect. We will have to look if this has any impact on the performance, but on my machine everything seemed fine.

**Review by sr258 — APPROVED** [review]

**Pull request merged**
