### PR TITLE
docs(development): make development easier by just running npm start

### PR DESCRIPTION
**Pull request by JPSchellenberg**
Hey,

as asked in #201 by @sr258 I simplified the start of the development-environment by starting the webpack-dev-server along with an instance of electron by running `npm start`.

### CODE REVIEW

**Review by sr258 — COMMENTED** [review]
If I run `npm start` on Windows 10 (Git bash) things don't work:

```sh
$ npm start

> lumi@0.0.1 start C:\Users\seret\Source\h5p\Lumi
> npx concurrently "node scripts/start.js" "npm run build:server && NODE_ENV=development node_modules/.bin/electron ."

[1] Der Befehl "scripts" ist entweder falsch geschrieben oder
[1] konnte nicht gefunden werden.
[3] Der Befehl "run" ist entweder falsch geschrieben oder    
[3] konnte nicht gefunden werden.
[4] Die Syntax f�r den Dateinamen, Verzeichnisnamen oder die Datentr�gerbezeichnung ist falsch.
[4] build:server exited with code 1    
[3] run exited with code 1
[1] scripts/start.js exited with code 1
[2] 
[2] Usage: npm <command>
[2]
[2] where <command> is one of:
[2]     access, adduser, audit, bin, bugs, c, cache, ci, cit,
[2]     clean-install, clean-install-test, completion, config,
[2]     create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
[2]     edit, explore, fund, get, help, help-search, hook, i, init,
[2]     install, install-ci-test, install-test, it, link, list, ln,
[2]     login, logout, ls, org, outdated, owner, pack, ping, prefix,
[2]     profile, prune, publish, rb, rebuild, repo, restart, root,
[2]     run, run-script, s, se, search, set, shrinkwrap, star,
[2]     stars, start, stop, t, team, test, token, tst, un,
[2]     uninstall, unpublish, unstar, up, update, v, version, view,
[2]     whoami
[2]
[2] npm <command> -h  quick help on <command>
[2] npm -l            display full usage info
[2] npm help <term>   search for help on <term>
[2] npm help npm      involved overview
[2]
[2] Specify configs in the ini-formatted file:
[2]     C:\Users\seret\.npmrc
[2] or on the command line via: npm <command> --key value
[2] Config info can be viewed via: npm help config
[2]
[2] npm@6.14.4 C:\Users\seret\Source\h5p\Lumi\node_modules\npm
[2] npm exited with code 1
```

**Comment by sr258** [comment]
I've found out that using double escapes in the script line in necessary in my Win 10 setup. Can you please check whether the script still works on MacOS?

Then the scripts to execute, but loading the page in the browser doesn't work at all. The first page is loaded fine, but all JavaScript resources don't load (504 Gateway Timeout). I've tried reloading the page after the first initial load and it still doesn't work. Once, things worked out, but I don't know why.

**Comment by JPSchellenberg** [comment]
Unfortunately it gives me this error:

```
[0] /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
[0] /bin/sh: -c: line 1: syntax error: unexpected end of file
[1] /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
[1] /bin/sh: -c: line 1: syntax error: unexpected end of file
[2] /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
[2] /bin/sh: -c: line 1: syntax error: unexpected end of file
[3] /bin/sh: run: command not found
[3] run exited with code 127
[2] "npm exited with code 2
[1] scripts/start.js" exited with code 2
[0] "node exited with code 2
[4] Error: Please specify 'description' in the application package.json ('/Users/Lipp/Lumi/Lumi/package.json')
[4]     at reportError (/usr/local/lib/node_modules/electron-builder/src/packager.ts:177:13)
[4]     at checkNotEmpty (/usr/local/lib/node_modules/electron-builder/src/packager.ts:182:9)
[4]     at Packager.checkMetadata (/usr/local/lib/node_modules/electron-builder/src/packager.ts:189:5)
[4]     at Packager.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/packager.ts:98:10)
[4]     at Generator.next (<anonymous>)
[4]     at runCallback (timers.js:705:18)
[4]     at tryOnImmediate (timers.js:676:5)
[4]     at processImmediate (timers.js:658:5)
[4] From previous event:
[4]     at tsAwaiter (/usr/local/lib/node_modules/electron-builder/src/util/awaiter.ts:10:47)
[4]     at Object.build (/usr/local/lib/node_modules/electron-builder/out/builder.js:135:12)
[4]     at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/out/build-cli.js:23:11)
[4]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[4]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[4]     at Module.load (internal/modules/cjs/loader.js:653:32)
[4]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[4]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[4]     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[4]     at startup (internal/bootstrap/node.js:283:19)
[4]     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[4] build exited with code 255
```

**Comment by JPSchellenberg** [comment]
Maybe we should separate it into `npm start:client` & `npm start:server`?

**Comment by sr258** [comment]
The current version simply starts electron the way you've used in the launch.json file. This works fine!

**Comment by JPSchellenberg** [comment]
The problem is, that two servers have to be started:
1) a webpack-dev-server which serves the client 
2) an electron instance which starts the backend server
currently `npm start` only starts the 2) backend server.

I would suggest to add to the documentation that one has to start two servers in different terminals. One with `npm run client` and `npm run server`.

**Comment by sr258** [comment]
That way I get Lumi working **in the browser**. However, the Electron window that opens when executing `npm run server` is empty:
image
Running it in the browser is completely fine, but the Electron window shouldn't open.

I think starting the server first makes more sense, as the client depends on it. We might also want to remove the `npm start` script as it doesn't work in all cases.

**Pull request closed without merging**
