### PR TITLE
fix(analytics-import): make only folders selectable (fixes #1368)

### LINKED ISSUE #1368: Lumi Analytics: Cannot import *.lumi file
Hi all,

after opening Lumi-Analytics and pressing the import button (".Lumi Dateien importieren" in german) a window opens in which you should choose the file.
In this window I only can select the folders that are shown in the left panel (i.e. recent, home, desktop, ...).
I cannot select any other folders, they are all grayed out.
Even with a right click it is not possible (see screenshot).

screenshot

Also if I select any of the folders in the left panel it is not possible for me to import a .lumis file.

 - OS: ubuntu 18.04
 - Lumi Version: 0.5.3 2021-03-17 (169)

1. Go to 'Lumi-Analytics'
2. Click on 'import'
3. Try to switch to a folder other than in the left panel
4. not possible

Selecting of any folder should be possible. Import should be possible.

### PR DESCRIPTION
**Pull request by JPSchellenberg**
Hey,

this should fix the problem when importing files into analytics. Now only folders are selectable on all OS.

### CODE REVIEW

**Comment by sr258** [comment]
While it also only shows a folder selector in Windows, the actual import doesn't work:

I get nothing if I select a folder with a bunch of .lumi files. (not even an error report). If I select a folder without lumi files I get the correct error message

**Comment by JPSchellenberg** [comment]
Does it work now?

**Comment by sr258** [comment]
No, it doesn't. The files are selected alright and they can also be parsed, I've checked. The problem must lie somewhere else. I get `TypeError: Cannot read property 'name' of undefined`, I guess from `userStatements[key][0].actor.account.name`. I've attached the files I'm using (generated with the current version of Lumi)

I don't think it's a good idea to use recursiveReadDir for this use case. If users have files from different content in subdirs it becomes impossible to load .lumi files in a directory.

[lumi files.zip](https://github.com/Lumieducation/Lumi/files/6222671/lumi.files.zip)

**Comment by JPSchellenberg** [comment]
> I don't think it's a good idea to use recursiveReadDir for this use case. If users have files from different content in subdirs it becomes impossible to load .lumi files in a directory.

The LMS that my school uses lets you download a .zip file for a class and every student has its subfolder. If we disable the recursive readdir I would have to copy every file into one folder, which would be very cumbersome. 

We could maybe display the second content-type instead of disregarding it.

**Comment by JPSchellenberg** [comment]
I fixed your issue and was able to import your files into analytics. If it works for you I would like to merge the PR to release the next version and then do a overhaul of the analytics module.

**Comment by sr258** [comment]
Importing works now. I also had to remove the file type filter to get it working on Linux. 

I think it would be good if we changed "Import .lumi files" to "Choose folder with .lumi files" (and correct als translations accordingly). This would make it more clear what to select in the next step.

After it is merged, you can release the next version.

**Pull request merged**
