### PR TITLE
fix(error handling): server deals more gracefully with invalid content

### LINKED ISSUE #1168: Client validation error when saving
When saving invalid content, the H5P core client rightly reports validation errors, but the saving progress bar is still running and Lumi doesn't report an error.

### PR DESCRIPTION
**Pull request by sr258**
Closes #1168

### CODE REVIEW

**Comment by JPSchellenberg** [comment]
I will add the redux stuff, so that a correct error message will be displayed as snackbar.

**Comment by sr258** [comment]
Currently only text fields are validated by h5p-server. Invalid text fields can be caused by:
- title not set (caught somewhere else)
- empty fields that have a minimum length
- regex strings not matches (e.g. in Advanced Blanks Snippets: image)

Weirdly the examples above currently pass validation in Lumi. When I played around, I saw this issue, not sure why it's not reproducible.

**Comment by JPSchellenberg** [comment]
I can not reproduce any errors.. Do you still want to merge this PR?

**Comment by sr258** [comment]
Yes, it improves error handling.

**Pull request merged**
