### PR TITLE
feat(analytics): add analytics and xapi-reporter

### PR DESCRIPTION
**Pull request by JPSchellenberg**
Hey,

I added a first draft of the analytics tool and the xapi reporter to the html export.
You can try everything by exporting a .html file, do the h5p, download the xapi-report as .lumi file and import the .lumi file in Lumi by using the Analytics tool.

### CODE REVIEW

**Comment by sr258** [comment]
Build & starting it works on Windows. The idea seems to work!

A few remarks: 
- The header for the table should include the title of the (sub)content and the human readable-version of the content type name.
- Clicking on the cards in the first page does nothing, you have to click on "start".
- Just tried [this](https://apps.zum.de/apps/englisch-die-uhrzeit) video with it and the .lumi file is  excessively large: it has 7,5 MBs! The reason seems to be that the base64 encoded resources are included; looks like some libraries include the params in the xAPI statement. We have to filter this out to make the files managable.
- it's great that the "player" in the html file limits the width of the content - for some content types. But it should be customizable, as Drag & Drop, Interactive Video, Course Presentation and other content types shouldn't be limited in screen size.
- What does the "Search" box search for? Students' names? This should be clearer
- If you put report files of different H5Ps into the same directory, the results are unexpected
- The main menu "File, Edit, etc." is still the one for the editor, even if the Analytics tool is open

**Comment by JPSchellenberg** [comment]
Ok, I fixed almost everything you mentioned, except the width. I will fix the e2e test tomorrow. Any other things that should be fixed?

**Comment by sr258** [comment]
- In Linux in the "import lumi report" file picker dialog I can't navigate into any subfolder. They are all grayed out and inaccessible. 
- the analytics tool scan all subfolders, which is difficult to understand at first, as it can result in errors if there are also .lumi files in the root folder
- if the window is smaller, the text overflow in boxes is not dealt with gracefully:
image
- the red color of low scores could be nicer
- the student search should not care about case (if I enter "sebastian" it doesn't find "Sebastian") and should trim whitespace at the beginning and end
- Hovering over a percentage could show the time the interaction was finished.
- The analytics app window becomes completely blank when I open the file picker and abort it.
- in the Reporter Client:
  - there should be some padding in the content card
  - pressing enter after entering your name should trigger the "ok"
- if you open a report of a h5p that is not composed of others (e.g. Fill in the Blanks) you still see the ubername (H5P.Blank 1.12) instead of the human readable version and the title.

Sidenote:
- We still need to publish the new version of @lumieducation/h5p-server: there are still incorrectly escaped characters in titles (&#039;)
-

**Comment by JPSchellenberg** [comment]
I fixed everything expect the design issues (red color, overflow, hovering over percentage) as I will have a designer have a look at it how to improve it.
What do you think about the functionality? Is it ready to be merged (or even released)?
I will update the h5p-library in a different PR.

**Comment by sr258** [comment]
This issue still exists: In Linux in the "import lumi report" file picker dialog I can't navigate into any subfolder. They are all grayed out and inaccessible. 

Maybe it's because of the fact the there is a selector "lumi report" which doesn't do anything?

**Comment by JPSchellenberg** [comment]
I guess it is due to the openDirectory setting in the OpenDialog from electron. Are there any .lumi files in the subfolder?

**Comment by sr258** [comment]
Sometimes there are, but you still can‘t select them.

**Pull request merged**
