### PR TITLE
feat(shortcuts): add shortcuts for copy&paste, select all (closes #230)

### LINKED ISSUE #230: Default keyboard accelerators are not working (cmd+a,cmd+c,cmd+v)
**Describe the bug**
Default keyboard accelerators are not working (cmd+a,cmd+c,cmd+v), so if you want to select or copy text it won't work.

**Environment (please complete the following information):**
 - 0.1.0

**Expected behavior**
Text should be selectable by cmd+a and copied with cmd+c & cmd+v.

**Additional context**
This is most likely due to undefined electron accelerators. 
Possible solution: https://medium.com/fantageek/supporting-copy-and-paste-in-electron-30bff250e564

### PR DESCRIPTION
**Pull request by JPSchellenberg**
As described in #230 it was not possible to copy&paste via cmd+c & cmd+v text or select it via cmd+a. Now keyboard accelerators are added to the menu for these actions under the label 'edit'.

### CODE REVIEW

**Comment by sr258** [comment]
The keyboard shortcut have always worked on my machine (Win 10), so I can't check whether this changes something.

The redo key mapping is unusual for Windows: Normally Redo is Ctrl+Y.

**Comment by JPSchellenberg** [comment]
Ok, on macOS it is cmd+shift+z, but I will see if I can make it different for windows.

**Comment by JPSchellenberg** [comment]
Ok, now it should be Ctrl+y for the redo action on windows. @sr258 can you confirm?

**Comment by sr258** [comment]
Now the Shortcut is correct.

The commands from the menu don't work at all, though. Sorry, didn't test this before, as the keyboard shortcuts worked:

lumi

**Review by sr258 — APPROVED** [review]
I think with my changes the menu will work as expected

**Pull request merged**
